export const TOGGLE_TIMER = 'toggle_timer'
export const UPDATE_TIMER = 'update_timer'
export const SET_ACTIVE_PLAYER = 'set_active_player'
export const TOGGLE_PAUSED = 'toggle_paused'
export const RESET_TIMERS = 'reset_timers'
export const SET_TIMERS = 'set_timers'
