export const UPDATE_TIMER = 'update_timer'
export const SET_ACTIVE_PLAYER = 'set_active_player'
export const TOGGLE_PAUSED = 'toggle_paused'
export const RESET_TIMERS = 'reset_timers'
export const SET_TIMERS = 'set_timers'
export const SET_GAME_MODE = 'set_game_mode'
export const CHANGE_TIMER_SETTINGS = 'change_settings'
export const ADD_TIME = 'add_time'
export const REDUCE_ADD_TIME = 'reduce_add_time'
export const ADD_MOVE = 'add_move'

export const CHANGE_VIEW = 'change_view'